name = "PolyglotFormalisms"
uuid = "8fd979ee-625c-447d-87f1-33af4d789de5"
version = "0.2.0"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
